# Generated by Django 4.2.2 on 2023-07-05 10:52

from django.db import migrations, models
import django.db.models.deletion

def load_initial_data(apps, schema_editor):
    Program = apps.get_model('admission', 'Program')
    programs = [
        {
            'code': 'BSCS',
            'name': 'Bachelor of Science in Computer Science',
            'duration': 4,
            'level': 'bachelor',
            'is_active': True,
        },
        {
            'code': 'BSIT',
            'name': 'Bachelor of Science in Information Technology',
            'duration': 4,
            'level': 'bachelor',
            'is_active': True,
        },
    ]

    for program_data in programs:
        program = Program(**program_data)
        program.save()

        
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('duration', models.IntegerField(default=4)),
                ('level', models.CharField(default='bachelor', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(load_initial_data),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('concat_year', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('concat_date', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.schoolyear')),
            ],
        ),
    ]
