# Generated by Django 4.2.2 on 2023-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
    ]
