# Generated by Django 4.2.2 on 2023-07-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_schoolyear_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_year',
            field=models.IntegerField(default=None),
        ),
    ]
