# Generated by Django 4.2.2 on 2023-07-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_criteria_autoadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
