# Generated by Django 4.2.2 on 2023-07-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_schoolyear_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
