# Generated by Django 4.2.2 on 2023-07-07 15:56

from django.db import migrations, models


def load_initial_data(apps, schema_editor):
    Department = apps.get_model('admission', 'Department')
    AcademicRank = apps.get_model('admission', 'AcademicRank')
    AdmissionRole = apps.get_model('admission', 'AdmissionRole')

    departments = ['Computer Science', 'Information Technology']
    academic_ranks = ['Instructor', 'Asst. Professor', 'Asso. Professor', 'Professor']
    admission_roles = ['Admission Officer', 'Staff', 'Interviewer']

    for department_name in departments:
        Department.objects.get_or_create(name=department_name)

    for academic_rank_name in academic_ranks:
        AcademicRank.objects.get_or_create(name=academic_rank_name)

    for admission_role_name in admission_roles:
        AdmissionRole.objects.get_or_create(name=admission_role_name)

class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_criteria_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
