# Generated by Django 4.2.2 on 2023-07-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_schoolyear_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionperiod',
            name='concat_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='concat_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
