# Generated by Django 4.2.2 on 2023-07-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_documentaryrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(null=True)),
                ('interview_time', models.CharField(default='', max_length=100)),
                ('setup', models.CharField(default='face-to-face', max_length=100)),
                ('venue', models.CharField(default='College of Computing Studies', max_length=255)),
                ('slot', models.IntegerField(default=30)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.program')),
                ('school_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.schoolyear')),
            ],
        ),
    ]
