# Generated by Django 4.2.2 on 2023-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_interviewslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewslot',
            name='interview_time',
            field=models.TimeField(null=True),
        ),
    ]
