# Generated by Django 4.2.2 on 2023-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type_name',
            field=models.CharField(blank=True, default='freshman', max_length=255),
        ),
    ]
