# Generated by Django 4.2.2 on 2023-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_uploadedphoto_personaladdress_contactpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_cet_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_economic_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_personal_info_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_personality_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_shs_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_study_complete',
            field=models.BooleanField(default=False),
        ),
    ]
