# Generated by Django 4.2.2 on 2023-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_uploadedphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(null=True, upload_to='students/'),
        ),
    ]
