# Generated by Django 4.2.2 on 2023-06-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_uploadedphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedphoto',
            name='photo_path',
        ),
    ]
