# Generated by Django 4.2.2 on 2023-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_uploadedphoto_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpoint',
            name='contact_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='contact_number',
            field=models.CharField(max_length=255),
        ),
    ]
