# Generated by Django 4.2.2 on 2023-06-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_contactpoint_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='students/'),
        ),
        migrations.DeleteModel(
            name='UploadedPhoto',
        ),
    ]
