# Generated by Django 4.2.2 on 2023-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_collegeentrancetest_report_of_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbackground',
            name='academic_awards_received',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='schoolbackground',
            name='class_rank',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolbackground',
            name='classroom_organization',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='schoolbackground',
            name='gpa_first_semester',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='schoolbackground',
            name='gpa_second_semester',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='schoolbackground',
            name='high_school_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolbackground',
            name='photo_grade',
            field=models.ImageField(null=True, upload_to='shs_card/'),
        ),
        migrations.AddField(
            model_name='schoolbackground',
            name='strand',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='schoolbackground',
            name='student_supreme_government',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolbackground',
            name='last_course_attended',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbackground',
            name='last_school_attended',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
