# Generated by Django 4.2.2 on 2023-07-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_schoolbackground_academic_awards_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_highest_academic_degree', models.CharField(max_length=100)),
                ('father_employment_status', models.CharField(max_length=100)),
                ('father_current_occupation', models.CharField(max_length=255)),
                ('mother_highest_academic_degree', models.CharField(max_length=100)),
                ('mother_employment_status', models.CharField(max_length=100)),
                ('mother_current_occupation', models.CharField(max_length=255)),
                ('computer', models.CharField(max_length=100)),
                ('internet_connection', models.CharField(max_length=100)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
