# Generated by Django 4.2.2 on 2023-07-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_economicstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicstatus',
            name='family_income',
            field=models.CharField(default='', max_length=100),
        ),
    ]
