# Generated by Django 4.2.2 on 2023-07-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_economicstatus_family_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField()),
                ('p2', models.IntegerField()),
                ('p3', models.IntegerField()),
                ('p4', models.IntegerField()),
                ('p5', models.IntegerField()),
                ('p6', models.IntegerField()),
                ('p7', models.IntegerField()),
                ('p8', models.IntegerField()),
                ('p9', models.IntegerField()),
                ('p10', models.IntegerField()),
                ('p11', models.IntegerField()),
                ('p12', models.IntegerField()),
                ('p13', models.IntegerField()),
                ('p14', models.IntegerField()),
                ('p15', models.IntegerField()),
                ('p16', models.IntegerField()),
                ('p17', models.IntegerField()),
                ('p18', models.IntegerField()),
                ('p19', models.IntegerField()),
                ('p20', models.IntegerField()),
                ('p21', models.IntegerField()),
                ('p22', models.IntegerField()),
                ('p23', models.IntegerField()),
                ('p24', models.IntegerField()),
                ('p25', models.IntegerField()),
                ('p26', models.IntegerField()),
                ('p27', models.IntegerField()),
                ('p28', models.IntegerField()),
                ('p29', models.IntegerField()),
                ('p30', models.IntegerField()),
                ('p31', models.IntegerField()),
                ('p32', models.IntegerField()),
                ('p33', models.IntegerField()),
                ('p34', models.IntegerField()),
                ('p35', models.IntegerField()),
                ('p36', models.IntegerField()),
                ('p37', models.IntegerField()),
                ('p38', models.IntegerField()),
                ('p39', models.IntegerField()),
                ('p40', models.IntegerField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
