# Generated by Django 4.2.2 on 2023-07-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_personalitytest_p1_alter_personalitytest_p10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField(null=True)),
                ('s2', models.IntegerField(null=True)),
                ('s3', models.IntegerField(null=True)),
                ('s4', models.IntegerField(null=True)),
                ('s5', models.IntegerField(null=True)),
                ('s6', models.IntegerField(null=True)),
                ('s7', models.IntegerField(null=True)),
                ('s8', models.IntegerField(null=True)),
                ('s9', models.IntegerField(null=True)),
                ('s10', models.IntegerField(null=True)),
                ('s11', models.IntegerField(null=True)),
                ('s12', models.IntegerField(null=True)),
                ('s13', models.IntegerField(null=True)),
                ('s14', models.IntegerField(null=True)),
                ('s15', models.IntegerField(null=True)),
                ('s16', models.IntegerField(null=True)),
                ('s17', models.IntegerField(null=True)),
                ('s18', models.IntegerField(null=True)),
                ('s19', models.IntegerField(null=True)),
                ('s20', models.IntegerField(null=True)),
                ('s21', models.IntegerField(null=True)),
                ('s22', models.IntegerField(null=True)),
                ('s23', models.IntegerField(null=True)),
                ('s24', models.IntegerField(null=True)),
                ('s25', models.IntegerField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
