# Generated by Django 4.2.2 on 2023-07-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_studyhabit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhabit',
            name='s25',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
