# Generated by Django 4.2.2 on 2023-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_admissionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='identification_card',
            field=models.ImageField(null=True, upload_to='identification/'),
        ),
    ]
