# Generated by Django 4.2.2 on 2023-07-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_student_identification_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbackground',
            name='combined_gpa',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
