# Generated by Django 4.2.2 on 2023-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_ccgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccgrade',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ccgrade',
            name='with_intervention',
            field=models.BooleanField(null=True),
        ),
    ]
