# Generated by Django 4.2.2 on 2023-07-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_admissionapplication_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeentrancetest',
            name='abstract_thinking_skills',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='collegeentrancetest',
            name='english_proficiency_skills',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='collegeentrancetest',
            name='overall_percentile_rank',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='collegeentrancetest',
            name='quantitative_skills',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='collegeentrancetest',
            name='reading_comprehension_skills',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='collegeentrancetest',
            name='science_process_skills',
            field=models.FloatField(),
        ),
    ]
