# Generated by Django 4.2.2 on 2023-06-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, default='student', max_length=255),
        ),
    ]
