# Generated by Django 4.2.2 on 2023-06-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_avatar_remove_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('key', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
