# Generated by Django 4.2.2 on 2023-07-01 04:04

from django.db import migrations, models

def load_initial_data(apps, schema_editor):
    class_ranks = apps.get_model('base', 'ClassRank')

    ranks = [
        'Top 5',
        'Top 10',
        'Top 20',
        'None',
    ]

    for rank_name in ranks:
        rank = class_ranks(name=rank_name)
        rank.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_studentsupremegovernment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
