# Generated by Django 4.2.2 on 2023-07-01 04:16

from django.db import migrations, models

def load_initial_data(apps, schema_editor):
    academic_awards = apps.get_model('base', 'AcademicAwards')

    awards = [
        'Highest Honor',
        'High Honor',
        'With Honor',
        'None',
    ]

    for award_name in awards:
        award = academic_awards(name=award_name)
        award.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_classrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
