# Generated by Django 4.2.2 on 2023-07-01 15:28

from django.db import migrations, models

def load_initial_data(apps, schema_editor):
    academic_degree = apps.get_model('base', 'AcademicDegree')

    degrees = [
        'Doctorate degree',
        'Master’s degree',
        'Bachelor’s degree',
        'Associate degree',
        'Trade/technical/vocational training',
        'Some college credit, no degree',
        'High school graduate, diploma or the equivalent',
        'Some high school, no diploma',
        'Nursery school to 8th grade',
        'No schooling completed',
        'Not Applicable (not known, deceased, etc.)',
    ]

    for degree_name in degrees:
        degree = academic_degree(name=degree_name)
        degree.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_academicawards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
