# Generated by Django 4.2.2 on 2023-07-01 15:36

from django.db import migrations, models

def load_initial_data(apps, schema_editor):
    academic_degree = apps.get_model('base', 'EmploymentStatus')

    degrees = [
        'Employed, working 40 hours or more per week (fulltime)',
        'Employed, working 1 to 39 hours or more per week (part-time)',
        'Self-employed (doing business, etc.)',
        'Not employed, looking for work',
        'Not employed, not looking for work',
        'Retired',
        'Disabled, not able to work',
        'Not Applicable (not known, deceased, etc.)',
    ]

    for degree_name in degrees:
        degree = academic_degree(name=degree_name)
        degree.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_academicdegree'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
